apiVersion: apps/v1
kind: Deployment
metadata: 
  name: cricketer-info
  labels: 
    app: cricketer-info
spec:
  selector:
    matchLabels: 
      app: cricketer-info     
  replicas: 1
  template:
    metadata: 
      labels:
        app: cricketer-info
    spec: 
      containers:
        - name: cricketer-info
          image: cricketer-info:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
  